# Generated by Django 5.0.8 on 2026-02-27 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='assets/')),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='gallery.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.tag')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='tags',
            field=models.ManyToManyField(related_name='assets', through='gallery.AssetTag', to='gallery.tag'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner', 'name'], name='gallery_col_owner_i_7420b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'asset')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner', 'name'], name='gallery_tag_owner_i_3748d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='assettag',
            unique_together={('asset', 'tag')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['collection', 'created_at'], name='gallery_ass_collect_665811_idx'),
        ),
    ]
